markdown: rdiscount
permalink: /:year-:month-:day/:title.html
url: http://www.dengck.com/
name: 邓成凯|Dennis Cheng kai Deng
author: Dennis Cheng kai Deng
qq: 
email: im@dengck.com
duoshuo: dechinkey
github: dechinkey
pygments: true
safe: true
paginate: 15